### ISSUE TITLE
Google Earth Engine -API issue in Rstudio (rgee)

### ISSUE THREAD

**Issue by Bhavani88** [jdbcode/ee-rgb-timeseries#1] opened 2021-03-06 17:17 UTC
Initializing Google Earth Engine:Error in py_call_impl(callable, dots$args, dots$keywords) : 
  UnknownApiNameOrVersion: name: earthengine  version: v1alpha

**Comment by jdbcode** [comment] 2021-03-08 14:37
Hello. This appears to be an issue with the `google-api-python-client` Python package. Please see this discussion:

https://github.com/giswqs/geemap/discussions/341#discussioncomment-436492

You are using `rgee` though, so the `pip` upgrade command may not work as expected -- I'm not sure about specifying the version for `rgee` -- you may have to go through `conda` and make sure you are in the environment that `rgee` is looking to. I'm including @csaybar and @giswqs for any recommendations.

**Comment by csaybar** [comment] 2021-03-08 17:41
I'm not able to reproduce this error neither in Linux or windows. But it seems that downgrading the google-api-python-client solve the problem as @giswqs explains in #giswqs/geemap#341

**Comment by jdbcode** [comment] 2021-03-28 17:33
The issue between `google-api-python-client` and `earthengine-api` has been resolved in recent versions.

**Closed as completed by jdbcode** 2021-03-28 17:33 UTC
